//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CategoryMaster
    {
        public int CategoryID { get; set; }
        [Required]
        public string Name { get; set; }
         [Required]
        public string Description { get; set; }
         [Required]
        public string PriceRange { get; set; }
         [Required]
        public Nullable<int> DisplayOrder { get; set; }
    }
}
