//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProductDetailsMaster 
    {
        public int ProductID { get; set; }
         [Required]
        public Nullable<int> CategoryID { get; set; }
         [Required]
        public string Name { get; set; }
         [Required]
        public string Description { get; set; }
         [Required]
        public Nullable<int> Quantity { get; set; }
         [Required]
        public Nullable<decimal> Price { get; set; }
         [Required]
        public Nullable<decimal> Discount { get; set; }
         [Required]
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
